// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmsrkboekyeieliemydc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdtc3JrYm9la3llaWVsaWVteWRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1ODc0NzUsImV4cCI6MjA2NDE2MzQ3NX0.HRi41VsLGFJDDsAhLDO7--u_N3OMtiK-UiS0Y6xzYGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);